In [8]:
from core.statusvariable import StatusVar
import scipy.interpolate


In [9]:
testtest = StatusVar(default=3.0e-6)

In [18]:
float(testtest)

Traceback (most recent call last):
  File "C:\Program Files (x86)\Qudi\logic\jupyterkernel\qzmqkernel.py", line 795, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-2a69728c6734>", line 1, in <module>
    float(testtest)
TypeError: float() argument must be a string or a number, not 'StatusVar'


In [ ]:
from core.configoption import ConfigOption
from core.statusvariable import StatusVar
from core.connector import Connector
from core.meta import InterfaceMetaclass


5

In [26]:
val = np.array([-5,-4,0,1,2,3,4,5])
max(np.abs(val))
bitsize = int(2**12)
shiftbits = 16-12   # 2 for marker, dac: 12 -> 2, dac: 14 -> 4
min_intval = -bitsize/2
max_intval =  bitsize/2 -1

max_u_samples = 1     # data should be normalized in (-1..1)

if max(abs(val)) > 1:
#     self.log.warning("Samples from sequencegenerator out of range. Normalizing to -1..1")
    # biggest_val = max([abs(np.min(val)), max(np.val)])
    biggest_val = max(np.abs(val))
    max_u_samples = biggest_val
# manual 8.22.4 Waveform Data Format in Direct Mode
# 2 bits LSB reserved for markers

mapper = scipy.interpolate.interp1d([-max_u_samples,max_u_samples],[min_intval, max_intval])
mapper(val).astype('int16') << 2

array([-8192, -6552,     0,  1636,  3272,  4912,  6548,  8188],
      dtype=int16)

In [13]:
mapper(val)

array([-2048.,   409.])

In [21]:
max_intval

2047.0

In [28]:
print(mapper(val).astype('int16') << 2)
print(mapper(val).astype('int16') << 4)

[-8192 -6552     0  1636  3272  4912  6548  8188]
[-32768 -26208      0   6544  13088  19648  26192  32752]


In [1]:
import visa
visa.__version__

'1.9.1'

In [3]:

keysight_M8195A.awg.query_delay = 5

keysight_M8195A.awg.query_delay

5

In [3]:

keysight_M8195A.awg.timeout = float('+inf') 


In [18]:
import time
start_time=time.time()
keysight_M8195A.query_bin(':MMEM:DATA? "C:\Program Files (x86)\Qudi\saved_pulsed_assets\sine_ch2.bin"')
end_time=time.time()
print("Time taken: {}".format(end_time-start_time))

Time taken: 0.035982370376586914


In [19]:
try:
    import time
    start_time=time.time()
    keysight_M8195A.query_bin(':MMEM:DATA? "C:\Program Files (x86)\Qudi\saved_pulsed_assets\rabi_ch2.bin"')
    end_time=time.time()
    print("Time taken: {}".format(end_time-start_time))
except Exception as err:
    end_time=time.time()
    print("Time taken: {}".format(end_time-start_time))    
    raise err

Time taken: 40.000715255737305


Traceback (most recent call last):
  File "C:\Program Files (x86)\Qudi\logic\jupyterkernel\qzmqkernel.py", line 795, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-b2089878d563>", line 10, in <module>
    raise err
  File "<ipython-input-19-b2089878d563>", line 4, in <module>
    keysight_M8195A.query_bin(':MMEM:DATA? "C:\Program Files (x86)\Qudi\saved_pulsed_assets\rabi_ch2.bin"')
  File "C:\Program Files (x86)\Qudi\hardware\awg\keysight_M8190A.py", line 1420, in query_bin
    return self.awg.query_binary_values(question, datatype='h', is_big_endian=False)
  File "C:\Program Files (x86)\Anaconda\envs\qudi\lib\site-packages\pyvisa\resources\messagebased.py", line 663, in query_binary_values
    header_fmt, expect_termination)
  File "C:\Program Files (x86)\Anaconda\envs\qudi\lib\site-packages\pyvisa\resources\messagebased.py", line 472, in read_binary_values
    block = self._read_raw()
  File "C:\Program Files (x86)\Anaconda\envs\qudi\lib\s

In [1]:
keysight_M8195A.awg.resource_info

(ResourceInfo(interface_type=<InterfaceType.tcpip: 6>, interface_board_number=0, resource_class='INSTR', resource_name='TCPIP0::localhost::hislip0::INSTR', alias=None), <StatusCode.success: 0>)

In [2]:
keysight_M8195A.awg.chunk_size

1024000

In [5]:
keysight_M8195A.awg.chunk_size  = 20480

In [3]:
keysight_M8195A.awg.chunk_size  = 2048000

In [3]:
keysight_M8195A.awg.timeout=40000

In [1]:
1024000*20e3 /1e9

20.48

In [2]:
keysight_M8195A._sequence_mode

True